### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-MoP/ElvUI-5.4.8#1]
Hi! Great job here! I was looking for a backported ElvUI for 5.4.8 forever... Will you be implementing the AddOnSkins, SwingBar, RaidMarkers, FriendListColor... etc. modules? It would be awesome to have this addon with the same, full range of functionality like ElvUI-WotLK! I haven't run into any bugs yet, and I could import my profile from 3.3.5, but somehow the Professions and the Talents page looks a bit weird...

**Comment by Apollyonn** [comment]
i'm very busy at the moment with work and other stuff so my spare time is very limited. Next month i will have plenty of free time and i might do all those things that you mentioned.

What do you mean weird? Can you upload a screenshot?

**Comment by nadszeg** [comment]
Thanks for the answer :) I did some editing in photoshop, so here's the imgur link: http://imgur.com/a/VeZak

**Comment by nadszeg** [comment]
I also added a screenshot of the plugins panel, because some of the plugins for other ports for other versions of the game work! (well, not all of them - the raidmarkers and the addonskins work)

**Comment by nadszeg** [comment]
I made a list of the plugins that would be cool if they were working with this version of ElvUI :) 
AddOnSkins
AuraBarsMovers
BagControl
Bunny(iLvl on Character frame, LoC visual - maybe CustomTweaks and Enhanced and this can be merged into one module)
ChannelAlerts
CustomTags
CustomTweaks
DataTextColors
Enhanced
FriendsListColor
MicrobarEnhancement
RaidMarkers
RightClick
SwingBar
