### ISSUE TITLE
Sort bank issue

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#14]
So this is a weird issue. When i place stuff in my bank i get the red text across the top like ability not ready or you cant use that.

But with sort bank tried to enchant item that didn't exist.

**Comment by TheRealestMcCoy** [comment]
![wowscrnshot_051617_151003](https://cloud.githubusercontent.com/assets/12252441/26123766/1379ab32-3a4a-11e7-960e-08bd30348e57.jpg)

**Comment by Apollyonn** [comment]
Does this happen with only ElvUI & ElvUI_Config Enabled?

**Comment by TheRealestMcCoy** [comment]
Havent tested it that way but it only happens when i sort bag.

**Comment by TheRealestMcCoy** [comment]
So just testing it with only elvui, elvui config and elvui enhanced on still get it.

**Comment by TheRealestMcCoy** [comment]
turned of enhanced still get it.

**Comment by TheRealestMcCoy** [comment]
turned off elvui config and still got it. So i have tested this all the way down to only Elvui on.

**Comment by Apollyonn** [comment]
I'm not sure if this is an elvui issue, i tried multiple times at different servers and i can't reproduce it.

**Comment by TheRealestMcCoy** [comment]
it may only be server side i was wondering if it was because i had some infinite dust in my bank?
