### ISSUE TITLE
Pet Battle, and some tracking

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-MoP/ElvUI-5.4.8#17]
Hi! I have the bottom bar enabled in ElvUI, but when I do pet battle, the bottom bar disappears... also when I want to track the digsites for archeology, after a /reload it's not tracked. It's the same with battle pets, they're always tracked, and when I disable their tracking and /reload, the minimap tracks them again. The archealogy digsite tracking is the same on the world map too.

**Comment by Apollyonn** [comment]
Top and bottom panels works as intented. Only the chat panels should be visible with the pet battle ui shows up.
The tracking problem is server side issue. I'm pretty sure it happens with default ui too.

**Comment by nadszeg** [comment]
Thx for the reply! I'll make a thread in their bugtracker then.
