### ISSUE TITLE
Taxi Frame

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#18]
Some times depending on where you are the flight master map aka taxi frame is a blank map. 
I tried the skin on off and back on and every time i turn it on it goes blank.

Taxi Map Skin On
![wowscrnshot_070817_144226](https://user-images.githubusercontent.com/12252441/27988266-e04fc5fe-63eb-11e7-8b4a-7e6b40d2f1ee.jpg)

Taxi Map Skin Off
![wowscrnshot_070817_144202](https://user-images.githubusercontent.com/12252441/27988267-ecc48504-63eb-11e7-8e26-79b00febe1aa.jpg)

**Comment by Apollyonn** [comment]
check now

**Comment by TheRealestMcCoy** [comment]
Seems to be better will close for now, but will reopen if it appears again.
