### ISSUE TITLE
Actionbar macro text

### ISSUE THREAD

**Issue by meneerprins** [ElvUI-MoP/ElvUI-5.4.8#2]
When I switch off macro text it keep appearing again after relog even when it's disabled. Thanks for this version btw, it seems much nicer than the 5.4.8 ElvUi, I hope this will be maintained :)

**Comment by Apollyonn** [comment]
I don't have such issue. Did you delete your old elvui before adding this one to your addons folder? If not then delete ElvUI and ElvUI_Config and add it again.

**Comment by TheRealestMcCoy** [comment]
When you say macro text do you mean what you named the macro? Are you trying to get the actual spell info to show?
If so use #showtooltip in the first line.

example

#showtooltip
/cast wrath

If that is your issue i hope it helps if not i am unsure what issue you mean.
I do think the #showtooltip was not needed in mop so it may be in the elvui some where.

**Comment by meneerprins** [comment]
What I mean is i have a macro for whatever spell or item that has a name and I put that macro on my actionbar, I want to hide the macro name text to be hidden with the ElvUI option. It is hidden but when i relog the macro name appears on the actionbar even when the 'show macro text' option is disabled. So I have to toggle the option on and off each time after I relog.

[http://i.imgur.com/IY2WZBo.jpg](http://i.imgur.com/IY2WZBo.jpg)

**Comment by TheRealestMcCoy** [comment]
That's weird i don't have that issue.

**Comment by TheRealestMcCoy** [comment]
Just curious this is a blizz thing have you tried to delete your cache

**Comment by Apollyonn** [comment]
whats the name of the server you are playing?
