### ISSUE TITLE
Raid Frames

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#21]
Roles dont show on raid frames

Every one shows as raid lead icon

Certain default raid debuffs dont show up now example voddoo doll from GArjal

**Comment by meneerprins** [comment]
Raid frames also have a different color sometimes and adjusting height etc. doesn't update in realtime.

**Comment by Apollyonn** [comment]
at RaidDebuff indicator untick Only Match SpellID and see if this fixes your problem.

**Comment by meneerprins** [comment]
Nice updates :) one thing that also didn't work for me was role icon on raid frames. (2 commits earlier)

**Comment by Apollyonn** [comment]
is everything ok now?

**Comment by TheRealestMcCoy** [comment]
Player role icons now appear will let you know about other issues

**Comment by TheRealestMcCoy** [comment]
dosent seem every one shows to be raid lead as either now.

**Comment by TheRealestMcCoy** [comment]
all my issues seem to be fixed as of now. WIll close
