### ISSUE TITLE
AFK return error

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#23]
Date: 2017-10-13 10:48:09
ID: 4
Error occured in: Global
Count: 1
Message: [string "CG_MinimapButton:OnHide"] line 1:
   attempt to index global 'this' (a nil value)
Debug:
   [string "*:OnHide"]:1:
      [string "*:OnHide"]:1
   [C]: Hide()
   ElvUI\modules\misc\afk.lua:87: SetAFK()
   ElvUI\modules\misc\afk.lua:165: ?()
   ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119:
      ...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:118

**Comment by Apollyonn** [comment]
I don't think this is elvui related, one of your addons must causing it. What is CG_MinimapButton?

**Comment by TheRealestMcCoy** [comment]
crap i thought that was turned off that cross fire gambling
