### ISSUE TITLE
toolkit?

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#24]
Date: 2017-10-17 19:09:25
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\ElvUI\core\toolkit.lua line 55:
   assertion failed!
Debug:
   [C]: ?
   ElvUI\core\toolkit.lua:55: Height()
   ...AddOns\ElvUI\modules\unitframes\elements\castbar.lua:292: SetCastTicks()
   ...AddOns\ElvUI\modules\unitframes\elements\castbar.lua:334: PostChannelStart()
   ...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:295:
      ...face\AddOns\ElvUI\Libraries\oUF\elements\castbar.lua:241

**Comment by TheRealestMcCoy** [comment]
this seems fixe dbut now i get lines for ticks on the cast bar. https://gyazo.com/f005589135790334e8a51da2a8f122e9

**Comment by Apollyonn** [comment]
Seems fine to me.
![wowscrnshot_102817_042054](https://user-images.githubusercontent.com/19589902/32129989-19fd498a-bb98-11e7-875a-779779b648a6.jpg)
![wowscrnshot_102817_042313](https://user-images.githubusercontent.com/19589902/32129968-dd5cf8ea-bb97-11e7-9cc5-a7beb29cb53d.jpg)

**Comment by TheRealestMcCoy** [comment]
i wonder if it has to do with me having the information panel enabled do you have that on?
it was fine till the last update for this issue.
