### ISSUE TITLE
Aspect of the Iron Hawk

### ISSUE THREAD

**Issue by Sdw8** [ElvUI-MoP/ElvUI-5.4.8#25]
On the panel of racks appears 2 Aspect of the Iron Hawk.
![image](https://user-images.githubusercontent.com/14907962/34483037-2103ddf2-efcd-11e7-91c0-6232224b78e5.png)

**Comment by Apollyonn** [comment]
![93bca0ad8ae9f3163c46b222f44825b5](https://user-images.githubusercontent.com/19589902/34545568-865896f0-f0f6-11e7-8b58-54d4c9238344.png)
For me its fine. Does it happen with blizzard ui also?

**Comment by Sdw8** [comment]
Oh, exactly. Blizzard ui also. It turns out nothing to do can not? I apologize for wrong issue.

**Comment by Apollyonn** [comment]
No worries :)
If it happens with blizzard ui that means its server side problem, nothing we can do about it.
