### ISSUE TITLE
Announce spell interrupts not working

### ISSUE THREAD

**Issue by Maczuga** [ElvUI-MoP/ElvUI-5.4.8#29]
![image](https://user-images.githubusercontent.com/544349/37140007-71a62d94-22b0-11e8-8b5a-b3b19d73318d.png)

Announce Interrupts have no effect. Tried "Party / Raid", "Say" with no success. Works fine on Curse's version.

**Comment by Apollyonn** [comment]
It works only while you are in group.

**Comment by Maczuga** [comment]
It was tested while in group. 
Example:
https://www.youtube.com/watch?v=8iZZrutZ7xY
