### ISSUE TITLE
Inspecting shows wrong quality border (using transmog instead of item)

### ISSUE THREAD

**Issue by Maczuga** [ElvUI-MoP/ElvUI-5.4.8#30]
Some screenshots:

1. Vigorsteel Spaulders shown as epic due to Scourgelord Shoulderplates being epic:
![image](https://user-images.githubusercontent.com/544349/37143777-69388f2e-22bc-11e8-8f8e-df4e5dd5833c.png)

2. Contender's Revenant Helm shown as epic due to Scourgelord Faceguard being epic:
![image](https://user-images.githubusercontent.com/544349/37143822-833fc2f2-22bc-11e8-8747-44e52f316bbb.png)

3. Bloodseeker's Axe shown as epic due to Torch of the Damned being epic:
![image](https://user-images.githubusercontent.com/544349/37143842-9726adc6-22bc-11e8-9696-8f7e381d7b3d.png)

**Comment by Apollyonn** [comment]
fixed
