### ISSUE TITLE
There is no "Micro Bar" for menu buttons 

### ISSUE THREAD

**Issue by ashido96** [ElvUI-MoP/ElvUI-5.4.8#37]
There is no "Micro Bar" for menu buttons (named as such in the Cataclysm version of this addon)

Cata screenshot: http://prntscr.com/kypj1j
MoP screenshot: http://prntscr.com/kypj8c

As you can see, the mop version of elvui has no movement allowed for for the menu buttons and the menu buttons are vertically distorted.

**Comment by snwflake** [comment]
Remove the ElvUI_MicrobarEnhancement plugin....
only thing it does, is break shit.
