### ISSUE TITLE
Elvui and Elvui Enhanced conflicts

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#4]
SO i switched from a version of 5.4.8 to this version since I use the Wotlk and Cata version you all work on. Now with this version is get alot of errors from elvui enhanced.
Some of this may be server side im not sure.

First Error: (Looks Elvui related.)
Error occured in: Global
Count: 1
Message: ..\AddOns\ElvUI\modules\datatexts\time.lua line 81:
   bad argument #3 to 'format' (string expected, got nil)
Debug:
   [C]: ?
   ElvUI\modules\datatexts\time.lua:81: onEnter()
   ...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:191:
      ...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:189

**I did not get these errors from enhanced till switching to this Elvui.
This version of enhanced elvui was from curse the last 5.4.8 version.**
2nd Error:

Message: ..\AddOns\ElvUI_Enhanced\config\options.lua line 314:
   attempt to index field 'minimap' (a nil value)
Debug:
   ElvUI_Enhanced\config\options.lua:314: MapOptions()
   ElvUI_Enhanced\config\options.lua:794: callback()
   ...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:87:
      ...\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:83
   [C]: ?
   [C]: LoadAddOn()
   ElvUI\init.lua:187: ToggleConfig()
   ElvUI\layout\layout.lua:379:
      ElvUI\layout\layout.lua:377

3rd Error:
Message: ...dOns\ElvUI_Enhanced\modules\datatexts\extratexts.lua line 201:
   attempt to index field '?' (a nil value)
Debug:
   ...dOns\ElvUI_Enhanced\modules\datatexts\extratexts.lua:201: HookClickMenuToEmptyDataText()
   ...dOns\ElvUI_Enhanced\modules\datatexts\extratexts.lua:255:
      ...dOns\ElvUI_Enhanced\modules\datatexts\extratexts.lua:247
   [C]: LoadDataTexts()
   ...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:22:
      ...terface\AddOns\ElvUI\modules\datatexts\datatexts.lua:14
   [C]: ?
   ElvUI\core\core.lua:970: InitializeModules()
   ElvUI\core\core.lua:1079: Initialize()
   ElvUI\init.lua:123:
      ElvUI\init.lua:122

**Comment by Apollyonn** [comment]
You are getting these errors because the ElvUI_Enhanced you are using from 3.3.5 or 4.3.4 or Curse are not 100% compatible with this version of ElvUi. In the near future i will make an ElvUI_Enhanced for this ElvUI.

**Comment by TheRealestMcCoy** [comment]
so this isnt a actual 5.4.8 elvui?
cause the elvui i use is 5.4.0 from curse forge version2.11

**Comment by Apollyonn** [comment]
This is an 5.4.8 elvui but is not the official one. This is a backported version. That means,  you cannot use old plugins like this https://wow.curseforge.com/projects/elvui-enhanced/files/749625 with this version because they are not compatible.

**Comment by Apollyonn** [comment]
Use this. https://github.com/ElvUI-MoP/ElvUI_Enhanced-5.4.8

**Comment by TheRealestMcCoy** [comment]
Will you be adding the farm bars and what not?

**Comment by TheRealestMcCoy** [comment]
The main features i would like to see added are the farm action bars, and there is one when questing it will default pick the quest reward item with the highest vendor value.

Farmer Module is the farmer one.

**Comment by Apollyonn** [comment]
maybe tomorrow

**Comment by TheRealestMcCoy** [comment]
No problem those are 2 of the main features i liked enhanced had in mop

**Comment by TheRealestMcCoy** [comment]
You are the man.
