### ISSUE TITLE
Dugi Questing Essential

### ISSUE THREAD

**Issue by Lemonadez** [ElvUI-MoP/ElvUI-5.4.8#41]
Minimap and Datatext disappear. Look screenshot below

https://codebin.us/i/qy5RCBH.jpg

It only happen if i use Dugi.
https://wow.curseforge.com/projects/dugi-questing-essential/files?filter-game-version=2020709689%3A474

**Comment by Thrombor2017** [comment]
I have exactly the same issue when using Zygor guides. Looks like it happened since the last update of Elvui ?
