### ISSUE TITLE
keybind text reversed/not showing empty buttons

### ISSUE THREAD

**Issue by lierox90** [ElvUI-MoP/ElvUI-5.4.8#42]
So looks like the button that is responsible to show keybind text over action bars works reversed now, when it’s turned off it shows text not when it’s on

Second thing is that option to show empty buttons doesn’t work anymore

**Comment by lierox90** [comment]
I also noticed that equipment section from enhanced is gone, no auto gear switching available

**Comment by lierox90** [comment]
Also looks like alternative power is somehow bugged, it shows some random letters and number while being all the time 100% full

**Comment by lierox90** [comment]
Also looks like keybind text is not working on class bar

**Comment by lierox90** [comment]
Also every switch of spec install window pops up

**Comment by snwflake** [comment]
First thing:
Please open new issues for every problem seperately.

> So looks like the button that is responsible to show keybind text over action bars works reversed now, when it’s turned off it shows text not when it’s on

Not on a clean install. Provide steps to reproduce the issue.

> Second thing is that option to show empty buttons doesn’t work anymore

Again. Working properly on a clean install.
