### ISSUE TITLE
Battle Pets and Mounts

### ISSUE THREAD

**Issue by Beefkek** [ElvUI-MoP/ElvUI-5.4.8#48]
Pets and mount don't show up immediately in their tabs after you learn them. Sometimes it takes like a day or two.

**Comment by Kkthnx** [comment]
If I understand this, this isn't a UI issue. Us developers do not have access to stuff like that. This sounds like a server issue wherever you are playing.

**Comment by Beefkek** [comment]
Idk, but it works fine when I disable elvui. I play on Tauri wow btw.

**Comment by snwflake** [comment]
Can't reproduce this whatsoever, neither with nor without ElvUI enabled.
Also playing on Evermoon Tauri.

Please disable all addons, except ElvUI and test again.
