### ISSUE TITLE
shadow orb bar disappears

### ISSUE THREAD

**Issue by chris4238** [ElvUI-MoP/ElvUI-5.4.8#49]
when i go through any instance portal or loading screen my shadow orb bar disappears.
when i change some classbar setting or /reload it pops back up.
on my warlock this doesnt happen
tried messing around with the settings but it didnt change anything
also tried to reset everything and set elvui up again and it also didnt help.

**Comment by Bunny67** [comment]
1

**Comment by Crumdidlyumshis** [comment]
test

**Comment by Bunny67** [comment]
1
