### ISSUE TITLE
Нет кнопки "выхода из техники"

### ISSUE THREAD

**Issue by maaniv** [ElvUI-MoP/ElvUI-5.4.8#57]
В версиях 2.0-2.3 нету кнопки "выхода из техники". На начальной территории монахов, запрыгнув на столб, кнопка для спрыгивания не появляется. В версии 1.24 все нормально.

**Comment by Apollyonn** [comment]
The leave vehicle button is no longer at the minimap settings but in the actionbar section.
![WoWScrnShot_040720_175339](https://user-images.githubusercontent.com/19589902/78684304-f83a1500-78f8-11ea-93ce-3e721d3b99ce.jpg)

**Comment by maaniv** [comment]
Button not appear in game.

**Comment by Apollyonn** [comment]
![WoWScrnShot_040720_180429](https://user-images.githubusercontent.com/19589902/78685377-56b3c300-78fa-11ea-871a-97598708d351.jpg)
can you see this mover?

**Comment by maaniv** [comment]
yes, i see mover

**Comment by Apollyonn** [comment]
So when you are in a vehicle nothing appears in the mover?

**Comment by maaniv** [comment]
yes
but with version 1.24 in same situation, button appears (on minimap)

**Comment by Apollyonn** [comment]
well no more minimap button, now its like this.

**Comment by maaniv** [comment]
I don't have exit vehicle button anywhere on screen, not only on minimap.

**Comment by Apollyonn** [comment]
Show me a screenshot of your UI while in Vehicle and also the settings that show the button enabled.
![WoWScrnShot_040720_205027](https://user-images.githubusercontent.com/19589902/78702588-7d312880-7911-11ea-8adb-eeee278c6e0e.jpg)

**Comment by maaniv** [comment]
![image](https://user-images.githubusercontent.com/6612937/78703528-01d07680-7913-11ea-9d90-a5ebdabf778e.png)
![image](https://user-images.githubusercontent.com/6612937/78703588-2298cc00-7913-11ea-8222-8ab385cf8486.png)

**Comment by Apollyonn** [comment]
Yeah thats not a vehicle. With blizzard UI is there any button that allows you to get out?

**Comment by maaniv** [comment]
![image](https://user-images.githubusercontent.com/6612937/78705599-64774180-7916-11ea-82eb-efb9c1943c74.png)
