### ISSUE TITLE
Standar blizzard unitframes (target, focus)

### ISSUE THREAD

**Issue by NonIdentifie** [ElvUI-MoP/ElvUI-5.4.8#58]
I downloaded the latest version and I have this problem, the target and focus do not change, I have everything marked in disable blizzard frames, I tried to disable and re-enable the target but it only works until I reload the game, then appears again the custom target blizzard uniframes, with the player unit I do not have that problem, also happens when I want to edit the raid I have to disable and enable unit to appear.

**Comment by Apollyonn** [comment]
Provide me a complete list of your enabled addons.

**Comment by damian2603** [comment]
unitframes>player>castbar and uncheck "Latency", it helped me

**Comment by Apollyonn** [comment]
My guess is that you import profiles from other expansions. Make a new profile and you are good.

**Comment by NonIdentifie** [comment]
> My guess is that you import profiles from other expansions. Make a new profile and you are good.

I've done a clean installation and everything works perfectly. Thank you.
