### ISSUE TITLE
Nameplates Debuffs

### ISSUE THREAD

**Issue by ghost** [ElvUI-MoP/ElvUI-5.4.8#59]
The nameplates debuffs disappear as soon as they're out of sight on the screen, they update when moving the mouse over them but it's still really annoying nonetheless.
It does only happen on enemies you don't have on target.
![WoWScrnShot_070520_000325](https://user-images.githubusercontent.com/67843614/86521580-2628ea00-be53-11ea-88a5-1f6d3df1d653.jpg)
![WoWScrnShot_070520_000327](https://user-images.githubusercontent.com/67843614/86521581-275a1700-be53-11ea-9dfc-a51dda842568.jpg)
![WoWScrnShot_070520_000329](https://user-images.githubusercontent.com/67843614/86521582-27f2ad80-be53-11ea-971b-36b2f45be2ea.jpg)

**Comment by Apollyonn** [comment]
This is not possible until legion expansion i think, basically in legion, nameplates act like unitframes.
In this expansion we check the combat log to get the auras on nameplates.
So the auras will only update on target and on mouseover.
