### ISSUE TITLE
Buff buttons on the minimap

### ISSUE THREAD

**Issue by nadszeg** [ElvUI-MoP/ElvUI-5.4.8#6]
Hi! Is there a way to turn off the stats, stamina,...etc. buttons on the minimap? I did it in the 3.3.5 version and when I imported the profile, even in the 4.3.4 version it worked, but in this 5.4.8 version, they are there. 
http://imgur.com/a/T6ADl

**Comment by Apollyonn** [comment]
Uncheck this:
![wowscrnshot_050917_005355](https://cloud.githubusercontent.com/assets/19589902/25827088/2516b248-3452-11e7-9f25-11ee26c8ff30.jpg)

**Comment by nadszeg** [comment]
Thank you! :)
