### ISSUE TITLE
Raid frames disappear on 25+ players

### ISSUE THREAD

**Issue by itsmekasta** [ElvUI-MoP/ElvUI-5.4.8#63]
v2.6

![](https://i.imgur.com/omgshzO.jpg)
![](https://i.imgur.com/Wg1oj89.pngl)

**Comment by Apollyonn** [comment]
in visibility settings delete [@raid31,exists] and it will show automatically when the raid has more than 25 players

**Comment by itsmekasta** [comment]
I completely forgot about that, cheers!
