### ISSUE TITLE
BossFrame Power doesn't display altPower anymore

### ISSUE THREAD

**Issue by snwflake** [ElvUI-MoP/ElvUI-5.4.8#69]
Probably broken since 0e2a86c7

![](https://i.imgur.com/YkKZTcB.jpg)

**Comment by Apollyonn** [comment]
It was an outdated feature since now you can control your alt power independedly from the unitframes.
Also showing players alt power to a boss frame its kinda odd.

**Comment by snwflake** [comment]
The previous alt power display on boss frames was nice, since you could see the progress independently from your current alt power (especially in the case of spoils), where progress would've been displayed for both groups on the boss frames seperately

Same deal with Lei-shen platform overload status
