### ISSUE TITLE
World Map quest box

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#7]
When you open the world map and have quests tracked the box is to dark to read.
![wowscrnshot_050817_183613](https://cloud.githubusercontent.com/assets/12252441/25828273/55c90e34-341d-11e7-97ca-c375053cc12d.jpg)

**Comment by nadszeg** [comment]
Sometimes the normal quest box text turns black for me too :/ :(

**Comment by Apollyonn** [comment]
Its a rare bug from the questlog skinning. I don't know what's causing it yet :(

**Comment by Apollyonn** [comment]
Did you disable the skin for QuestLog?

**Comment by TheRealestMcCoy** [comment]
Yes didnt help

**Comment by TheRealestMcCoy** [comment]
There is also a issue with the trainer frame the learn button sits up in the spells for a profession.

**Comment by Apollyonn** [comment]
![wowscrnshot_050917_015745](https://cloud.githubusercontent.com/assets/19589902/25829048/868628a6-345c-11e7-9af4-46e9a6454414.jpg)
I have no issues with the world map quest text. What addons are you using? Try to log with only ElvUI and ElvUI_Config and see if the problem persist.

Same with the trainer button.

**Comment by TheRealestMcCoy** [comment]
Yep same issue only elvui active. 
![wowscrnshot_050817_191350](https://cloud.githubusercontent.com/assets/12252441/25829144/85924658-3422-11e7-9ec1-63cf9e8ff237.jpg)

**Comment by Apollyonn** [comment]
Is QuestFrames skin enabled?

**Comment by TheRealestMcCoy** [comment]
It is unchecked. I thought it would help but didnt

**Comment by TheRealestMcCoy** [comment]
![wowscrnshot_050817_191815](https://cloud.githubusercontent.com/assets/12252441/25829268/1db0eaf2-3423-11e7-9726-9f985a8988cc.jpg)
![wowscrnshot_050817_191818](https://cloud.githubusercontent.com/assets/12252441/25829267/1dad3ede-3423-11e7-86b1-619087366854.jpg)

**Comment by Apollyonn** [comment]
Did you try only ElvUI & ElvUI_Config with Quest Frames skin checked?

**Comment by TheRealestMcCoy** [comment]
ya ive had it unchecked for a few days i just deleted my cache and it did not change

**Comment by TheRealestMcCoy** [comment]
I had a actual 5.4.8 version from wow freaks but it had chat errors and what not. I switched to yours when i found it since i use your wotlk and cata one

**Comment by Apollyonn** [comment]
It should be like this
![wowscrnshot_050917_022228](https://cloud.githubusercontent.com/assets/19589902/25829430/b7351e74-345e-11e7-8cef-f99b8652c3a8.jpg)
![wowscrnshot_050917_022250](https://cloud.githubusercontent.com/assets/19589902/25829433/b86ef468-345e-11e7-9af4-09394fc2f3a5.jpg)

**Comment by TheRealestMcCoy** [comment]
ok so turning the quest skin back on fixes it.

**Comment by TheRealestMcCoy** [comment]
I dont think that should be doing that

**Comment by Apollyonn** [comment]
The code for skinning the quest rewards and quest text font is located at the questlog skin. World map doesn't have a seperate questlog, it uses the default one with a different layout. So when you disable the questlog skin, the world map quest elements are not skinned.
