### ISSUE TITLE
chat can't display cyrillic/korean/chinese anymore

### ISSUE THREAD

**Issue by snwflake** [ElvUI-MoP/ElvUI-5.4.8#72]
pre-rework (1.24)

![](https://i.imgur.com/9nvNefc.png)

post-rework (7fd6e95)

![](https://i.imgur.com/RJP0TCT.png)

**Comment by Apollyonn** [comment]
![WoWScrnShot_072720_202222](https://user-images.githubusercontent.com/19589902/88572077-45c4c400-d047-11ea-8126-a7d97316ea55.jpg)
Works fine for me. maybe you have a font that doesn't support these languages

**Comment by snwflake** [comment]
mhm...unlikely, since I'm using the same font as before, Roboto.
Gonna do some checking after raid.

**Comment by snwflake** [comment]
closed due to what appears to be a user error
