### ISSUE TITLE
Spellflash not working

### ISSUE THREAD

**Issue by drew88syn** [ElvUI-MoP/ElvUI-5.4.8#73]
Hi
After this "new" update, the spellflash not working anymore for me. 
Any fix?

**Comment by Apollyonn** [comment]
In the addon open SpellFLashCore.lua file, go to line `271` and change this
`local LibActionButton = LibStub:GetLibrary("LibActionButton-1.0", true)`
to
`local LibActionButton = LibStub:GetLibrary("LibActionButton-1.0-ElvUI", true)`
