### ISSUE TITLE
Blurry chat and unitframes font 

### ISSUE THREAD

**Issue by Aqinog** [ElvUI-MoP/ElvUI-5.4.8#74]
Hey, I've just updated from the ElvUI from curseforge to this version of ElvUI but for some reason the font of the chat (mainly) and the uniframes (slightly) looks kind of blurry and much worse than with the curse version. The 1st screenshot (1) is with the ElvUI from curse, the 2nd (2) is with this ElvUI backport. I have had this issue as soon as I installed the backport and can't get rid of it through tweaking the font settings.

(1) ![WoWScrnShot_052720_082513](https://user-images.githubusercontent.com/69145216/89168966-e4887d80-d57d-11ea-9d39-8ea64e3e2294.jpg)

(2) ![WoWScrnShot_072620_015521](https://user-images.githubusercontent.com/69145216/89168984-ea7e5e80-d57d-11ea-92f9-f9dc5270edf9.jpg)

**Comment by snwflake** [comment]
make sure you're 1. using the same font as before
and 2. change the outline from `NONE` to `OUTLINE`

**Comment by Aqinog** [comment]
After further testing it seems this only happens when the text is of a similar color to the background. However the outline setting makes the font look terrible. Is there a way to work around that ?
