### ISSUE TITLE
Party Pet Alignment and Spacing

### ISSUE THREAD

**Issue by itsmekasta** [ElvUI-MoP/ElvUI-5.4.8#75]
Any way to change the spacing to 0 and align multiple pets beneath the player frames via in-game menu?
Similar to the default frames.

[Example here](https://thumbs.gfycat.com/EmbarrassedInsignificantIbex-mobile.mp4)

**Comment by Apollyonn** [comment]
You can use Raid Pets. Just adjust the visibility to show also in party.
![WoWScrnShot_090520_032103](https://user-images.githubusercontent.com/19589902/92292678-1eef8c80-ef27-11ea-9782-3e94401f5794.jpg)
