### ISSUE TITLE
ElvUI + Clique

### ISSUE THREAD

**Issue by Beefkek** [ElvUI-MoP/ElvUI-5.4.8#77]
You can't click on save/cancel if you try to make a custom bind with clique.

How to replicate:
1. Have both Elvui and Clique
2. Open Clique
3. Click on Bind Other > Run Custom Macro
4. Try to click Save or Cancel

**Comment by Apollyonn** [comment]
it was a problem with the skin. its fixed here https://github.com/ElvUI-MoP/ElvUI_AddOnSkins-5.4.8/commit/93fdfb06a308a4fe0d6af7ad76ccb991a485c13a
