### ISSUE TITLE
Chat issues

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#8]
So the server has a /global chat. And i get this error every time I login after you join the channel.
Message: ..\AddOns\ElvUI\modules\chat\chat.lua line 1086:
   bad argument #1 to 'format' (string expected, got nil)
Debug:
   [C]: ?
   ElvUI\modules\chat\chat.lua:1086: ChatFrame_MessageEventHandler()
   ElvUI\modules\chat\chat.lua:1345: ChatFrame_OnEvent()
   ElvUI\modules\chat\chat.lua:1351:
      ElvUI\modules\chat\chat.lua:1350
Locals:
(*temporary) = nil
(*temporary) = 4
(*temporary) = "4. LookingForGroup"
(*temporary) = "string expected, got nil"

**Comment by Apollyonn** [comment]
If you are playing on tauri wow its server side issue.

open chat module with a text editor and add this under line 1075
if arg1 == "NOT_IN_LFG" then return; end

**Comment by TheRealestMcCoy** [comment]
So it should now look like this?
elseif (type == "CHANNEL_NOTICE") then
		if arg1 == "NOT_IN_LFG" then return; end
			local globalstring = _G["CHAT_"..arg1.."_NOTICE_BN"];
			if ( not globalstring ) then
				globalstring = _G["CHAT_"..arg1.."_NOTICE"];

**Comment by TheRealestMcCoy** [comment]
That seemed to have fixed the tauri issue. Thanks
