### ISSUE TITLE
Trainer Frame not working properly on 1440p

### ISSUE THREAD

**Issue by Nefarion** [ElvUI-MoP/ElvUI-5.4.8#81]
![image](https://user-images.githubusercontent.com/542084/113509119-2118d880-9554-11eb-9562-e950347a8487.png)

**Comment by Nefarion** [comment]
i tried a few fixes:
Changing [ClassTrainerFrameInset:Kill()](https://github.com/ElvUI-MoP/ElvUI-5.4.8/blob/821bb9a6e69a671bb254a7ceeb084c411c5ae5ce/ElvUI/Modules/Skins/Blizzard/Trainer.lua#L17) to 	`ClassTrainerFrameInset:StripTextures()` leads to this
![image](https://user-images.githubusercontent.com/542084/113509268-f2e7c880-9554-11eb-8929-4f0b16bf14f6.png)

**Comment by Nefarion** [comment]
At the end, with this diff for [Trainer.lua](https://github.com/ElvUI-MoP/ElvUI-5.4.8/blob/master/ElvUI/Modules/Skins/Blizzard/Trainer.lua)
``` diff
@@ -13,10 +13,8 @@ local function LoadSkin()
 	ClassTrainerFrame:Height(472)
 
 	ClassTrainerFrameBottomInset:StripTextures()
+	ClassTrainerFrameBottomInset:Point("TOPLEFT", ClassTrainerFrame, 5, -130)
 
+	ClassTrainerFrameInset:StripTextures()
+	ClassTrainerFrameInset:Point("TOPLEFT", ClassTrainerFrame, 5, -80)
-	ClassTrainerFrameInset:Kill()
 	ClassTrainerFramePortrait:Kill()
 
 	S:HandleButton(ClassTrainerTrainButton)

```

I get this result: 
![image](https://user-images.githubusercontent.com/542084/113511208-0435d280-955f-11eb-9b27-91eaf7f77494.png)

Hope this helps?

**Comment by Apollyonn** [comment]
Should be ok now. I can't test it since i don't have a 1440p monitor atm.
If you have similar problems or if you see something that doesn't feel right with other skins please open another issue.
