### ISSUE TITLE
Right click not working on action bars

### ISSUE THREAD

**Issue by Mainbexel** [ElvUI-MoP/ElvUI-5.4.8#82]
Is it intentionally? Or I'm the only one having this issue?
Also tried with /luaerror on, still not working.

**Comment by CraftedRO** [comment]
Uncheck in elvui settings : Action Bars > Right click self cast
![WoWScrnShot_072921_154937](https://user-images.githubusercontent.com/24683355/127495178-8e35de78-e92d-47a6-b82d-19d43ae0d4a7.jpg)

**Comment by Mainbexel** [comment]
It was unchecked. The thing is with self cast enabled there are things that working like Hearthstone. But if the self cast is unchecked (like in default settings) it's completely ignoring my right clicks for some reason lol. It also working fine on the default blizz ui. I know it sounds lame, never had this kind of issue. Anyway thanks for the response.
