### ISSUE TITLE
Tillers Rep

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-MoP/ElvUI-5.4.8#9]
The tillers show rep as hostile friendly revered. When they are used diff. Example friend/best friend.

**Comment by Apollyonn** [comment]
I don't understand.

**Comment by TheRealestMcCoy** [comment]
Like one of the tillers Gina Mud Claw.
I am and acquaintance with here but the rep bar says Hostile
![wowscrnshot_051017_201548](https://cloud.githubusercontent.com/assets/12252441/25926475/7c948d76-35bd-11e7-825b-6dd2553b2a55.jpg)

**Comment by TheRealestMcCoy** [comment]
They have Friend Ship Levels.
Friendship levels:
Stranger: 0-8400
Acquaintance: 8400-16800
Buddy: 16800-25200
Friend: 25200-33600
Good Friend: 33600-42000
Best Friend: 42000-42999

**Comment by TheRealestMcCoy** [comment]
10 Tiller NPCs have Friendship bars, which are similar to reputation but don't have normal Normal/Friendly distinctions. Instead, there are six segments of 8400 friendship each, with the best level obtainable at 42000 friendship. While gaining friendship, you'll also gain some Tillers reputation.

http://www.wowhead.com/news=205091/mists-of-pandaria-guide-to-the-tillers#friendship-with-tiller-npcs
